### ISSUE TITLE
Trata-se de um ORM ou Adapter?

### ISSUE THREAD

**Issue by JoaoLeopoldino** [acidiney/brokher#2]
Olá, 
Pela descrição desta lib, notei que provavelmente trata-se de um [Adapter](https://en.wikipedia.org/wiki/Adapter_pattern) e não um ORM(Object-relational mapping ). A ser o caso, acredito que importa mudar a descrição até para que mais pessoas consigam encontrar esta lib.

**Comment by EriksonGM** [comment]
@JoaoLeopoldino , concordo com a tua abordagem.

Nao misturar as coisas.

@acidiney , vem trabalhar e resolver a tua bagunça

**Comment by acidiney** [comment]
@JoaoLeopoldino muito obrigado pela issue. Realmente é um adaptar.

Porém a seleção da descrição foi intencional, pois para muitos conseguem perceber do que se trata pela descrição.

Assim, sendo... Não pretendo alterar.

Novamente obrigado pela issue. Vou deixar no readme que o uso do nome ORM é intencional embora não "seja" um.
